-- Performance indexes.

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_memberships_org ON organization_memberships(organization_id);
CREATE INDEX idx_memberships_user ON organization_memberships(user_id);
CREATE INDEX idx_invitations_org ON organization_invitations(organization_id);
CREATE INDEX idx_invitations_token ON organization_invitations(token_hash);
CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE INDEX idx_sessions_token ON sessions(token_hash);
CREATE INDEX idx_sessions_refresh ON sessions(refresh_token_hash);
CREATE INDEX idx_security_events_user ON security_events(user_id, created_at);
CREATE INDEX idx_auth_codes_expires ON authorization_codes(expires_at);
CREATE INDEX idx_password_resets_user ON password_reset_tokens(user_id);
CREATE INDEX idx_plans_product ON plans(product_id);
CREATE INDEX idx_prices_plan ON prices(plan_id);
CREATE INDEX idx_features_product ON features(product_id);
CREATE INDEX idx_plan_entitlements_plan ON plan_entitlements(plan_id);
CREATE INDEX idx_releases_product_channel ON product_releases(product_id, channel, status);
CREATE INDEX idx_licenses_org ON licenses(organization_id);
CREATE INDEX idx_licenses_product ON licenses(product_id);
CREATE INDEX idx_licenses_status ON licenses(status);
CREATE INDEX idx_licenses_key_hash ON licenses(key_hash);
CREATE INDEX idx_license_activations_license ON license_activations(license_id);
CREATE INDEX idx_license_activations_domain ON license_activations(domain_normalized);
CREATE INDEX idx_license_events_license ON license_events(license_id, created_at);
CREATE INDEX idx_subscriptions_org ON subscriptions(organization_id);
CREATE INDEX idx_subscriptions_stripe ON subscriptions(stripe_subscription_id);
CREATE INDEX idx_subscription_items_sub ON subscription_items(subscription_id);
CREATE INDEX idx_orders_org ON orders(organization_id);
CREATE INDEX idx_invoices_org ON invoices(organization_id);
CREATE INDEX idx_payments_org ON payments(organization_id);
CREATE INDEX idx_websites_org ON websites(organization_id);
CREATE INDEX idx_websites_domain ON websites(domain_normalized);
CREATE INDEX idx_installations_website ON website_installations(website_id);
CREATE INDEX idx_ai_ledger_org ON ai_credit_ledger(organization_id);
CREATE INDEX idx_ai_ledger_created ON ai_credit_ledger(created_at);
CREATE INDEX idx_ai_ledger_org_created ON ai_credit_ledger(organization_id, created_at DESC, id DESC);
CREATE INDEX idx_usage_events_idempotency ON usage_events(organization_id, idempotency_key);
CREATE INDEX idx_notifications_user ON notifications(user_id, created_at DESC);
CREATE INDEX idx_support_tickets_org ON support_tickets(organization_id, status);
CREATE INDEX idx_audit_org ON audit_logs(organization_id);
CREATE INDEX idx_audit_correlation ON audit_logs(correlation_id);
CREATE INDEX idx_audit_created ON audit_logs(created_at);
CREATE INDEX idx_api_keys_org ON api_keys(organization_id);
CREATE INDEX idx_api_keys_hash ON api_keys(key_hash);
CREATE INDEX idx_webhooks_type ON webhook_events(event_type, processed_at);
CREATE INDEX idx_webhook_subs_status ON webhook_subscriptions(status);
CREATE INDEX idx_webhook_deliveries_sub ON webhook_deliveries(subscription_id, created_at DESC);
